/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Jogador;
import Model.TabelaPontuacao;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos ruben
 */
public class Tela extends javax.swing.JFrame {
    
    protected TabelaPontuacao tabela = new TabelaPontuacao();

    /**
     * Creates new form Tela
     */
    public Tela() {
        atualizarTabela();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButtonNovoJogo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableJogos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel5.setText("Resultados da  Temporada");

        jButtonNovoJogo.setText("Novo Jogo");
        jButtonNovoJogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonNovoJogoMouseClicked(evt);
            }
        });
        jButtonNovoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoJogoActionPerformed(evt);
            }
        });

        jTableJogos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jogo", "Placar", "Mínimo da Temporada", "Máxima da Temporada", "Quebra recorde min.", "Quebra recorde máx."
            }
        ));
        jTableJogos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableJogosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableJogos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonNovoJogo))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNovoJogo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoJogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNovoJogoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonNovoJogoMouseClicked

    private void jButtonNovoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoJogoActionPerformed
        // TODO add your handling code here:
      NovoJogo nt = new NovoJogo(tabela, this);
      nt.setVisible(true);
    }//GEN-LAST:event_jButtonNovoJogoActionPerformed

    private void jTableJogosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableJogosMouseClicked
        // TODO add your handling code here:
        atualizarTabela();
    }//GEN-LAST:event_jTableJogosMouseClicked

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        atualizarTabela();
    }//GEN-LAST:event_formFocusGained

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
       try {
            // TODO add your handling code here:
            tabela.gravarArquivo("../dados/dados.txt");
        } catch (IOException ex) {
            
        }
    }//GEN-LAST:event_formWindowClosing

    public void atualizarTabela(){
        Jogador jogador = tabela.retornarUltimoJogo();
        if (jogador instanceof Jogador){
            DefaultTableModel model =(DefaultTableModel) jTableJogos.getModel();
            model.addRow(new Object[]{jogador.getID(),jogador.getPlacar(),jogador.getRecordeMin(), jogador.getRecordeMax(), jogador.getQtdRecordeQuebradoMin(), jogador.getQtdRecordeQuebradoMax()});         
        }        
    }
    
    public void carregarTabelaCompleta(){
        for (int i = 0; i < tabela.jogos.size(); i++) {
            Jogador jogador = tabela.jogos.get(i);
            if (jogador instanceof Jogador){
                DefaultTableModel model =(DefaultTableModel) jTableJogos.getModel();
                model.addRow(new Object[]{jogador.getID(),jogador.getPlacar(),jogador.getRecordeMin(), jogador.getRecordeMax(), jogador.getQtdRecordeQuebradoMin(), jogador.getQtdRecordeQuebradoMax()});         
            }        
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Tela tela = new Tela();
                try {
                    tela.tabela.carregarArquivo("../dados/dados.txt");
                    tela.carregarTabelaCompleta();
                } catch (IOException ex) {
                    
                }
                tela.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNovoJogo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableJogos;
    // End of variables declaration//GEN-END:variables
}
